#!/bin/bash

# @file     makeTests
# @brief    Скрипт проведения тестов для проверки утилиты jls
# @param    arg Путь до jls

# Для подавления ошибок jls типа Aborted (core dumped)
set +o notify

#
# Константы
#

# @brief    Директория скрипта
readonly COMMON_SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# @brief    Название скрипта
readonly COMMON_SCRIPT_NAME="$(basename "$0")"

# @brief    Директория с тестовым окружением
readonly COMMON_TESTS_DIR="$COMMON_SCRIPT_DIR/../tests"

# @brief    Путь до утилиты jls
readonly COMMON_JLS="$1"

#
# Цвета
#

# @brief    Красный цвет
readonly COMMON_RED='\033[31m'

# @brief    Желтый цвет
readonly COMMON_YELLOW='\033[33m'

# @brief    Зеленый цвет
readonly COMMON_GREEN='\033[32m'

# @brief    Сброс цвета
readonly COMMON_RESET='\033[0m'

#
# Общие переменные
#

# @brief    Флаг наличия valgrind в системе
COMMON_IS_VALGRIND_EXISTS=0

# @brief    Список тестов и их аргументов
# @warning  Элементы в списке расположены как [i % 2 != 0] = "Название теста" [i % 2 == 0] = "Аргумент для jls" и тд.
COMMON_TESTS_ARGS_LIST=()

#
# Функции
#

# @brief    Точка входа в скрипт
function main()
{
    if ! prepare
    then
        return 1
    fi

    if (( ${#COMMON_TESTS_ARGS_LIST[@]} % 2 != 0 ))
    then
        echo "Fatal error: COMMON_TESTS_ARGS_LIST is even. Must be odd"
        return 1
    fi

    local TESTS_RESULT_LIST=()
    for ((i = 0; i < ${#COMMON_TESTS_ARGS_LIST[@]}; i+=2))
    do
        local TEST="${COMMON_TESTS_ARGS_LIST[$i]}"
        local ARG="${COMMON_TESTS_ARGS_LIST[$i + 1]}"

        TESTS_RESULT_LIST+=("${TEST}Compare")
        performCompareTest "${TEST}Compare" "$ARG"
        TESTS_RESULT_LIST+=("$?")

        if [ $COMMON_IS_VALGRIND_EXISTS -eq 1 ]
        then
            TESTS_RESULT_LIST+=("${TEST}MemoryLeak")
            performMemoryLeakTest "${TEST}MemoryLeak" "$ARG"
            TESTS_RESULT_LIST+=("$?")
        fi
    done

    local TEST_NAME_MAX_LENGTH=0
    local TEST_NUMBER_MAX_LENGTH=0
    for ((i = 0; i < ${#TESTS_RESULT_LIST[@]}; i+=2))
    do
        local TEST_NAME=${TESTS_RESULT_LIST[$i]}
        if [[ ${#TEST_NAME} -gt $TEST_NAME_MAX_LENGTH ]]
        then
            TEST_NAME_MAX_LENGTH=${#TEST_NAME}
        fi

        local TEST_NUMBER=$((i / 2))
        if [[ ${#TEST_NUMBER} -gt $TEST_NUMBER_MAX_LENGTH ]]
        then
            TEST_NUMBER_MAX_LENGTH=${#TEST_NUMBER}
        fi
    done

    echo -e "\n\n\nSummary:"

    for ((i = 0; i < ${#TESTS_RESULT_LIST[@]}; i+=2))
    do
        local TEST="${TESTS_RESULT_LIST[$i]}"
        local RESULT="${TESTS_RESULT_LIST[$i + 1]}"
        local TEST_NUMBER=$((i / 2))

        if [[ $RESULT -eq 0 ]]
        then
            echo -en "$COMMON_GREEN"
            RESULT="Passed"
        else
            echo -en "$COMMON_RED"
            RESULT="Failed"
        fi

        printf "[%*d] %-*s %s" "$TEST_NUMBER_MAX_LENGTH" "$TEST_NUMBER" "$TEST_NAME_MAX_LENGTH" "$TEST" "$RESULT"

        echo -e "$COMMON_RESET"
    done

    return 0
}

# @brief    Функция подготовки рабочего окружения
# @details  Данная функция выполняет проверку существования jls,
#               проверку существования тестовой среды, её очистку от логов тестов
#               проверку наличия valgrind и
#               формирует список тестов в переменной <COMMON_TESTS_ARGS_LIST>
# @return   Возвращает 0 в случае успешной подготовки рабочего окружения.
#               В противном случае, возвращет 1
function prepare()
{
    if ! [ -x "$COMMON_JLS" ]
    then
        echo -e "jls doesn't exist! Use:\n\tmake\nThen pass path to jls as first argument"
        return 1
    fi

    if ! [ -d "$COMMON_TESTS_DIR" ]
    then
        echo -e "Test environment doesn't exist! Use:\n\tmake testEnv"
        return 1
    fi

    COMMON_TESTS_ARGS_LIST=()

    # Тест на текущей директории
    COMMON_TESTS_ARGS_LIST+=("Empty")
    COMMON_TESTS_ARGS_LIST+=("")

    # Тест на jls
    COMMON_TESTS_ARGS_LIST+=("Self")
    COMMON_TESTS_ARGS_LIST+=("$COMMON_JLS")

    # Тест на корне ФС
    COMMON_TESTS_ARGS_LIST+=("Root")
    COMMON_TESTS_ARGS_LIST+=("/")

    local TEST=""
    for TEST in "$COMMON_TESTS_DIR/"*
    do
        if [ -d "$TEST" ]
        then
            COMMON_TESTS_ARGS_LIST+=("$(basename "$TEST")")
            COMMON_TESTS_ARGS_LIST+=("$COMMON_TESTS_DIR/$(basename "$TEST")")
        fi
        if [ -f "$TEST" ]
        then
            rm "$COMMON_TESTS_DIR/$(basename "$TEST")"
        fi
    done

    if command -v valgrind >> /dev/null 2>&1
    then
        COMMON_IS_VALGRIND_EXISTS=1
    fi

    return 0
}

# @brief    Функция выполнения теста, сравнивающего вывод jls и ls -l
# @details  Данная функция выполняет: <br>
#               - Запуск jls   с ARG в качестве аргумента и записывает вывод в <COMMON_TESTS_DIR>/<TEST>.jls <br>
#               - Запуск ls -l с ARG в качестве аргумента и записывает вывод в <COMMON_TESTS_DIR>/<TEST>.ls  <br>
#               - Запуск diff <COMMON_TESTS_DIR>/<TEST>.ls <COMMON_TESTS_DIR>/<TEST>.jls и записывает вывод в <COMMON_TESTS_DIR>/<TEST>.diff <br>
# @param    TEST Название теста
# @param    ARG  Аргументы запуска
# @param    ARG используется данной функцией без двойных кавычек 
# @return   Возвращает 0, если вывод jls и ls одинаковы.
#               В противном случае, возвращает 1
function performCompareTest()
{
    local TEST="ANON"
    local ARG=""

    if [ -n "$1" ]
    then
        TEST="$1"
    fi

    if [ -n "$2" ]
    then
        ARG="$2"
    fi

    local JLS_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.jls"
    local LS_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.ls"
    local DIFF_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.diff"

    echo -en "${COMMON_YELLOW}"
    echo     "=====${TEST}====="
    echo     "ARG              is $ARG"
    echo     "JLS_OUTPUT_FILE  is $JLS_OUTPUT_FILE"
    echo     "LS_OUTPUT_FILE   is $LS_OUTPUT_FILE"
    echo     "DIFF_OUTPUT_FILE is $DIFF_OUTPUT_FILE"
    echo     "Command: \"$COMMON_JLS\" $ARG >> \"$JLS_OUTPUT_FILE\" 2>&1"
    echo -e  "${COMMON_RESET}"

    if ! truncate -s 0 "$JLS_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $JLS_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! truncate -s 0 "$LS_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $LS_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! truncate -s 0 "$DIFF_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $DIFF_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    "$COMMON_JLS" $ARG >> "$JLS_OUTPUT_FILE" 2>&1
    ls -l         $ARG >> "$LS_OUTPUT_FILE"  2>&1

    if ! diff  "$LS_OUTPUT_FILE" "$JLS_OUTPUT_FILE" >> "$DIFF_OUTPUT_FILE" 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Test failed: output of jls and ls -l differs"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    echo -en "${COMMON_GREEN}"
    echo -n  "Test passed"
    echo -e  "${COMMON_RESET}"

    return 0
}

# @brief    Функция выполнения теста на утечки памяти
# @details  Данная функция выполняет проверку наличия valgrind в системе, 
#               запуск jls с ARG в качестве аргумента при помощи valgrind и 
#               записывает вывод в <COMMON_TESTS_DIR>/<TEST>.valgrind
# @param    TEST Название теста
# @param    ARG  Аргумент запуска
# @param    ARG используется данной функцией без двойных кавычек
# @return   Возвращает 0, если valgrind не обнаружил утечек памяти у jls.
#               В противном случае, возвращает 1
function performMemoryLeakTest()
{
    local TEST="ANON"
    local ARG=""

    if [ -n "$1" ]
    then
        TEST="$1"
    fi

    if [ -n "$2" ]
    then
        ARG="$2"
    fi

    if [ $COMMON_IS_VALGRIND_EXISTS -eq 0 ]
    then
        return 1
    fi    
    
    local VALGRIND_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.valgrind"
    local JLS_OUTPUT_FILE="/tmp/$COMMON_SCRIPT_NAME.jls.output"

    echo -en "${COMMON_YELLOW}"
    echo     "=====${TEST}====="
    echo     "ARG                  is $ARG"
    echo     "VALGRIND_OUTPUT_FILE is $VALGRIND_OUTPUT_FILE"
    echo     "Command: valgrind --leak-check=full --error-exitcode=1 --log-file=\"$VALGRIND_OUTPUT_FILE\" \"$COMMON_JLS\" $ARG >> /dev/null 2>&1"
    echo -e  "${COMMON_RESET}"

    if ! truncate -s 0 "$VALGRIND_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $VALGRIND_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! truncate -s 0 "$JLS_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $JLS_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! valgrind --leak-check=full --error-exitcode=1 --log-file="$VALGRIND_OUTPUT_FILE" "$COMMON_JLS" $ARG >> "$JLS_OUTPUT_FILE" 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed. Memory-leaks detected"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    echo -en "${COMMON_GREEN}"
    echo -n  "Test passed"
    echo -e  "${COMMON_RESET}"

    return 0
}

#
# Точка входа в скрипт
#

main
exit $?
