#!/bin/bash

# @file     makeTests
# @brief    Скрипт проведения тестов для проверки утилиты jls
# @param    COMMON_JlS    Путь до jls
# @param    DESIRED_TESTS Список желаемых тестов. Если пуст, будут выполнены все тесты из <COMMON_TESTS_DIR>

#
# Константы
#

# @brief    Директория скрипта
readonly COMMON_SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# @brief    Название скрипта
readonly COMMON_SCRIPT_NAME="$(basename "$0")"

# @brief    Директория с тестовым окружением
readonly COMMON_TESTS_DIR="$COMMON_SCRIPT_DIR/../tests"

# @brief    Путь до утилиты jls
readonly COMMON_JLS="$1"; shift

# @brief    Режимы запуска jls и ls
readonly COMMON_MODES_LIST=("Terminal"
                            "File")

#
# Цвета
#

# @brief    Красный цвет
readonly COMMON_RED='\033[31m'

# @brief    Желтый цвет
readonly COMMON_YELLOW='\033[33m'

# @brief    Зеленый цвет
readonly COMMON_GREEN='\033[32m'

# @brief    Сброс цвета
readonly COMMON_RESET='\033[0m'

#
# Общие переменные
#

# @brief    Флаг наличия valgrind в системе
COMMON_IS_VALGRIND_EXISTS=0

# @brief    Флаг наличия meld в системе
COMMON_IS_MELD_EXISTS=0

# @brief    Список тестов и их аргументов
# @warning  Элементы в списке расположены как [i % 2 != 0] = "Название теста" [i % 2 == 0] = "Аргумент для jls" и тд.
COMMON_TESTS_ARGS_LIST=()

# @brief    Режим тестов
COMMON_MODE="${COMMON_MODES_LIST[0]}"

#
# Функции
#

# @brief    Точка входа в скрипт
# @param    DESIRED_TESTS Список желаемых тестов. Если пуст, будут выполнены все тесты из <COMMON_TESTS_DIR>
function main()
{
    local DESIRED_TESTS=("$@")

    if ! prepare
    then
        return 1
    fi

    if (( ${#COMMON_TESTS_ARGS_LIST[@]} % 2 != 0 ))
    then
        echo "Fatal error: COMMON_TESTS_ARGS_LIST is even. Must be odd"
        return 1
    fi

    local TESTS_RESULT_LIST=()
    local MODE=""
    for MODE in "${COMMON_MODES_LIST[@]}"
    do
        COMMON_MODE="$MODE"
        for ((i = 0; i < ${#COMMON_TESTS_ARGS_LIST[@]}; i+=2))
        do
            local TEST="${COMMON_TESTS_ARGS_LIST[$i]}"
            local ARG="${COMMON_TESTS_ARGS_LIST[$i + 1]}"

            local IS_COMPARE_DESIRED=0
            local IS_MEMLEAK_DESIRED=0

            if [[ "${#DESIRED_TESTS[@]}" -ne 0 ]]
            then                
                local DESIRED_TEST=""
                for DESIRED_TEST in "${DESIRED_TESTS[@]}"
                do
                    if [ "$DESIRED_TEST" == "${TEST}${COMMON_MODE}Compare" ]
                    then
                        IS_COMPARE_DESIRED=1
                    fi

                    if [ "$DESIRED_TEST" == "${TEST}${COMMON_MODE}MemoryLeak" ]
                    then
                        IS_MEMLEAK_DESIRED=1
                    fi
                done
            else
                IS_COMPARE_DESIRED=1
                IS_MEMLEAK_DESIRED=1
            fi

            if [[ "$IS_COMPARE_DESIRED" == "1" ]]
            then
                TESTS_RESULT_LIST+=("${TEST} ${COMMON_MODE} Compare")
                performCompareTest "${TEST}${COMMON_MODE}Compare" "$ARG"
                TESTS_RESULT_LIST+=("$?")
            fi

            if [[ "$COMMON_IS_VALGRIND_EXISTS" == "1" && "$IS_MEMLEAK_DESIRED" == "1" ]]
            then
                TESTS_RESULT_LIST+=("${TEST} ${COMMON_MODE} MemoryLeak")
                performMemoryLeakTest "${TEST}${COMMON_MODE}MemoryLeak" "$ARG"
                TESTS_RESULT_LIST+=("$?")
            fi
        done
    done

    local TEST_NAME_MAX_LENGTH=0
    local TEST_NUMBER_MAX_LENGTH=0
    for ((i = 0; i < ${#TESTS_RESULT_LIST[@]}; i+=2))
    do
        local TEST_NAME="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f1)"
        if [[ ${#TEST_NAME} -gt $TEST_NAME_MAX_LENGTH ]]
        then
            TEST_NAME_MAX_LENGTH=${#TEST_NAME}
        fi

        local TEST_NUMBER=$((i / 2))
        if [[ ${#TEST_NUMBER} -gt $TEST_NUMBER_MAX_LENGTH ]]
        then
            TEST_NUMBER_MAX_LENGTH=${#TEST_NUMBER}
        fi
    done

    local TEST_MODE_MAX_LENGTH=0
    for MODE in "${COMMON_MODES_LIST[@]}"
    do
        if [[ ${#MODE} -gt $TEST_MODE_MAX_LENGTH ]]
        then
            TEST_MODE_MAX_LENGTH=${#MODE}
        fi
    done

    local TEST_TYPE_MAX_LENGTH=0
    local TYPE=""
    local TEST_TYPES_LIST=("MemoryLeak"
                           "Compare")
    for TYPE in "${TEST_TYPES_LIST[@]}"
    do
        if [[ ${#TYPE} -gt $TEST_TYPE_MAX_LENGTH ]]
        then
            TEST_TYPE_MAX_LENGTH=${#TYPE}
        fi
    done

    local PASSED_COUNT=0
    local FAILED_COUNT=0
    echo -e "\n\n\nSummary:"
    for ((i = 0; i < ${#TESTS_RESULT_LIST[@]}; i+=2))
    do
        local TEST="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f1)"
        local MODE="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f2)"
        local TYPE="$(echo "${TESTS_RESULT_LIST[$i]}" | cut -d ' ' -f3)"
        local RESULT="${TESTS_RESULT_LIST[$i + 1]}"
        local TEST_NUMBER=$((i / 2))

        if [[ $RESULT -eq 0 ]]
        then
            echo -en "$COMMON_GREEN"
            RESULT="Passed"
            ((PASSED_COUNT++))
        else
            echo -en "$COMMON_RED"
            RESULT="Failed"
            ((FAILED_COUNT++))
            
            local LS_FILE="$COMMON_TESTS_DIR/${TEST}${MODE}${TYPE}.ls"
            local JLS_FILE="$COMMON_TESTS_DIR/${TEST}${MODE}${TYPE}.jls"

            if [ "$COMMON_IS_MELD_EXISTS" == "1" ] && [ "${TYPE}" == "Compare" ] && [ -f "$LS_FILE" ] && [ -f "$JLS_FILE" ]
            then
                meld -n "$LS_FILE" "$JLS_FILE" &
            fi
        fi

        printf "[%*d] %-*s %-*s %-*s %s" "$TEST_NUMBER_MAX_LENGTH" "$((TEST_NUMBER + 1))" "$TEST_NAME_MAX_LENGTH" "$TEST" "$TEST_MODE_MAX_LENGTH" "$MODE" "$TEST_TYPE_MAX_LENGTH" "$TYPE" "$RESULT"

        echo -e "$COMMON_RESET"
    done

    echo

    if [[ "$FAILED_COUNT" -gt 0 ]]
    then
        echo -en "$COMMON_RED"
        echo -n  "Failed $FAILED_COUNT/$((${#TESTS_RESULT_LIST[@]}/2))"
        echo -e  "$COMMON_RESET"
    fi

    if [[ "$PASSED_COUNT" -gt 0 ]]
    then
        echo -en "$COMMON_GREEN"
        echo -n  "Passed $PASSED_COUNT/$((${#TESTS_RESULT_LIST[@]}/2))"
        echo -e  "$COMMON_RESET"
    fi

    echo

    return 0
}

# @brief    Функция подготовки рабочего окружения
# @details  Данная функция выполняет проверку существования jls,
#               проверку существования тестовой среды, её очистку от логов тестов
#               проверку наличия valgrind, meld и
#               формирует список тестов в переменной <COMMON_TESTS_ARGS_LIST>
# @return   Возвращает 0 в случае успешной подготовки рабочего окружения.
#               В противном случае, возвращет 1
function prepare()
{
    if ! [ -x "$COMMON_JLS" ]
    then
        echo -e "jls doesn't exist! Use:\n\tmake\nThen pass path to jls as first argument"
        return 1
    fi

    if ! [ -d "$COMMON_TESTS_DIR" ]
    then
        echo -e "Test environment doesn't exist! Use:\n\tmake testEnv"
        return 1
    fi

    local TESTS_LIST=()
    local TESTS_LIST_SORTED=()

    TESTS_LIST=("$COMMON_TESTS_DIR"/*)
    mapfile -t TESTS_LIST_SORTED < <(
        printf '%s\n' "${TESTS_LIST[@]}" \
        | awk '{ print length, $0 }'     \
        | sort -rn                       \
        | cut -d' ' -f2-
    )

    COMMON_TESTS_ARGS_LIST=()

    # Тест на текущей директории
    COMMON_TESTS_ARGS_LIST+=("Empty")
    COMMON_TESTS_ARGS_LIST+=("")

    # Тест на jls
    COMMON_TESTS_ARGS_LIST+=("Self")
    COMMON_TESTS_ARGS_LIST+=("$COMMON_JLS")

    # Тест на /usr/bin
    COMMON_TESTS_ARGS_LIST+=("UsrBin")
    COMMON_TESTS_ARGS_LIST+=("/usr/bin")

    # Тест с двойными кавычками
    COMMON_TESTS_ARGS_LIST+=("DoubleQuotes")
    COMMON_TESTS_ARGS_LIST+=("\"\"")

    # Тест с несколькими аргументами
    COMMON_TESTS_ARGS_LIST+=("FewArguments")
    COMMON_TESTS_ARGS_LIST+=("NonExistent1 $COMMON_SCRIPT_DIR/$COMMON_SCRIPT_NAME $COMMON_SCRIPT_DIR /usr/bin/echo NonExistent2 NonExistent3")

    local TEST=""
    for TEST in "${TESTS_LIST_SORTED[@]}"
    do
        if [ -d "$TEST" ]
        then
            COMMON_TESTS_ARGS_LIST+=("$(basename "$TEST")")
            COMMON_TESTS_ARGS_LIST+=("$COMMON_TESTS_DIR/$(basename "$TEST")")
        fi
        if [ -f "$TEST" ]
        then
            rm "$COMMON_TESTS_DIR/$(basename "$TEST")"
        fi
    done

    if command -v valgrind >> /dev/null 2>&1
    then
        COMMON_IS_VALGRIND_EXISTS=1
    fi

    if command -v meld >> /dev/null 2>&1
    then
        COMMON_IS_MELD_EXISTS=1
    fi

    return 0
}

# @brief    Функция выполнения теста, сравнивающего вывод jls и ls -l
# @details  Данная функция выполняет: <br>
#               - Запуск jls   с ARG в качестве аргумента и записывает вывод в <COMMON_TESTS_DIR>/<TEST>.jls <br>
#               - Запуск ls -l с ARG в качестве аргумента и записывает вывод в <COMMON_TESTS_DIR>/<TEST>.ls  <br>
#               - Запуск diff <COMMON_TESTS_DIR>/<TEST>.ls <COMMON_TESTS_DIR>/<TEST>.jls и записывает вывод в <COMMON_TESTS_DIR>/<TEST>.diff <br>
# @param    TEST Название теста
# @param    ARG  Аргументы запуска
# @param    ARG используется данной функцией без двойных кавычек 
# @return   Возвращает 0, если вывод jls и ls одинаковы.
#               В противном случае, возвращает 1
function performCompareTest()
{
    local TEST="ANON"
    local ARG=""

    if [ -n "$1" ]
    then
        TEST="$1"
    fi

    if [ -n "$2" ]
    then
        ARG="$2"
    fi

    local JLS_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.jls"
    local LS_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.ls"
    local DIFF_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.diff"

    echo

    echo -en "${COMMON_YELLOW}"
    echo     "=====${TEST}====="
    echo     "ARG              is $ARG"
    echo     "JLS_OUTPUT_FILE  is $JLS_OUTPUT_FILE"
    echo     "LS_OUTPUT_FILE   is $LS_OUTPUT_FILE"
    echo -n  "DIFF_OUTPUT_FILE is $DIFF_OUTPUT_FILE"
    echo -e  "${COMMON_RESET}"

    if ! truncate -s 0 "$JLS_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $JLS_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! truncate -s 0 "$LS_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $LS_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! truncate -s 0 "$DIFF_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $DIFF_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    local JLS_INFO=""
    local  LS_INFO=""
    local TMP_FILE="/tmp/$COMMON_SCRIPT_NAME.info"    

    local JLS_MODE="--test-mode "
    local LS_MODE=""
    if [ "$COMMON_MODE" == "${COMMON_MODES_LIST[0]}" ]
    then
        JLS_MODE+="--safe-mode --color-mode"
        #TODO удалить -w 80
        LS_MODE+="--quoting-style=shell --color=always -w 80"
    fi

    /usr/bin/time -q -f "uptime=%e sec | peak-memory=%M KiB" -o "$TMP_FILE" "$COMMON_JLS" $JLS_MODE $ARG >> "$JLS_OUTPUT_FILE" 2>&1
    JLS_INFO=$(< "$TMP_FILE")
    rm -f "$TMP_FILE"

    /usr/bin/time -q -f "uptime=%e sec | peak-memory=%M KiB" -o "$TMP_FILE" ls -l $LS_MODE $ARG >> "$LS_OUTPUT_FILE" 2>&1
    LS_INFO=$(< "$TMP_FILE")
    rm -f "$TMP_FILE"

    echo "jls info: $JLS_INFO"
    echo "ls  info: $LS_INFO"

    if ! diff  "$LS_OUTPUT_FILE" "$JLS_OUTPUT_FILE" >> "$DIFF_OUTPUT_FILE" 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Test failed: output of jls and ls -l differs"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    echo -en "${COMMON_GREEN}"
    echo -n  "Test passed"
    echo -e  "${COMMON_RESET}"

    return 0
}

# @brief    Функция выполнения теста на утечки памяти
# @details  Данная функция выполняет проверку наличия valgrind в системе, 
#               запуск jls с ARG в качестве аргумента при помощи valgrind и 
#               записывает вывод в <COMMON_TESTS_DIR>/<TEST>.valgrind
# @param    TEST Название теста
# @param    ARG  Аргумент запуска
# @param    ARG используется данной функцией без двойных кавычек
# @return   Возвращает 0, если valgrind не обнаружил утечек памяти у jls.
#               В противном случае, возвращает 1
function performMemoryLeakTest()
{
    local TEST="ANON"
    local ARG=""

    if [ -n "$1" ]
    then
        TEST="$1"
    fi

    if [ -n "$2" ]
    then
        ARG="$2"
    fi

    if [ $COMMON_IS_VALGRIND_EXISTS -eq 0 ]
    then
        return 1
    fi    
    
    local VALGRIND_OUTPUT_FILE="$COMMON_TESTS_DIR/${TEST}.valgrind"
    local JLS_OUTPUT_FILE="/tmp/$COMMON_SCRIPT_NAME.jls.output"

    echo

    echo -en "${COMMON_YELLOW}"
    echo     "=====${TEST}====="
    echo     "ARG                  is $ARG"
    echo -n  "VALGRIND_OUTPUT_FILE is $VALGRIND_OUTPUT_FILE"
    echo -e  "${COMMON_RESET}"

    if ! truncate -s 0 "$VALGRIND_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $VALGRIND_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    if ! truncate -s 0 "$JLS_OUTPUT_FILE" >> /dev/null 2>&1
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed to create $JLS_OUTPUT_FILE file"
        echo -e  "${COMMON_RESET}"
        return 1
    fi
    
    local VALGRIND_RESULT=0;

    valgrind --leak-check=full --error-exitcode=3 --log-file="$VALGRIND_OUTPUT_FILE" "$COMMON_JLS" $ARG >> "$JLS_OUTPUT_FILE" 2>&1
    VALGRIND_RESULT=$?
    if [[ "$VALGRIND_RESULT" -eq 3 ]]
    then
        echo -en "${COMMON_RED}"
        echo -n  "Failed. Memory-leaks detected"
        echo -e  "${COMMON_RESET}"
        return 1
    fi

    echo -en "${COMMON_GREEN}"
    echo -n  "Test passed"
    echo -e  "${COMMON_RESET}"

    return 0
}

#
# Точка входа в скрипт
#

main "$@"
exit $?
